
[package]
name = "wasm-nn"
authors = ["0xArty <0xArty@proton.me>"]
version = "0.1.0"
edition = "2021"
description = """
wasm-nn is a deep learning framework for WebAssembly.
"""
documentation = "https://docs.rs/wasm-nn"
repository = "https://github.com/0xArty/wasm-nn"
readme = "README.md"
license = "MIT"
keywords = ["machine-learning", "neural-network", "deep-learning", "wasm"]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size